[General]
grab_focus = true

[UI]
# Define o tamanho baseado na documentação que você enviou
window_size = 400 300

[Finders]
default_finder = desktop
desktop_icons = true

[Colors]
# Aqui é onde a mágica do Wal acontece
# O Hyprlauncher busca cores hexadecimais simples
background = {background.strip}
border = {color1.strip}
text = {foreground.strip}
selected_bg = {color1.strip}
selected_text = {background.strip}